---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: Create clones from template
  register: out_clone
  vars:

    _notes_source:
      - "vmm={{ inventory_hostname }}"
      - "{{ properties.notes | d('') }}"
      - "{{ item.value.notes | d('') }}"
      - "{{ item.value.properties.notes | d('') }}"
      - "class={{ item.value.class | d([]) | join(',') }}"
    _notes: "{{ _notes_source | select | join(' ') }}"

    _properties_source:
      - "{{ properties | d({}) }}"
      - "{{ item.value.properties | d({}) }}"
    _properties_combined: >-
      {{ _properties_source
         | community.general.remove_keys(target=['notes'])
         | select
         | combine(recursive=true) }}
    _properties: >-
      {% for k, v in _properties_combined.items() %}
      {{ k }}={{ v }}
      {% endfor %}
      notes="{{ _notes }}"

  vbotka.freebsd.iocage:
    state: cloned
    clone_from: "{{ item.value.clone_from }}"
    name: "{{ item.key }}"
    properties: "{{ _properties }}"
  loop: "{{ clones | dict2items }}"
  loop_control:
    label: "{{ item.key }} {{ item.value.clone_from }}"

- name: "Debug clones from template debug2={{ debug2 }}"
  when: debug2 | bool
  ansible.builtin.debug:
    var: out_clone

- name: Set iocage_jails
  ansible.builtin.set_fact:
    iocage_jails: "{{ ansible_facts.iocage_jails }}"

- name: Start clones
  vars:
    iocage_jails_started: "{{ iocage_jails
                              | dict2items
                              | selectattr('value.state', 'eq', 'up')
                              | map(attribute='key')
                              | list }}"
    _jails: "{{ iocage_jails | difference(iocage_jails_started) | list }}"
  changed_when: false
  register: out_start
  when:
    - not dry_run | bool
    - _jails | length > 0
  ansible.builtin.command:
    cmd: >
      iocage start
      {{ _jails | join(' ') }}

- name: "Debug start clones debug2={{ debug2 }}"
  when: debug2 | bool
  ansible.builtin.debug:
    var: out_start
