- name: Get iocage_jails from module.
  when: "iocage_jails_source == 'module'"
  block:

    - name: Query iocage module.
      vbotka.freebsd.iocage:

    - name: Reject jails with empty notes.
      ansible.builtin.set_fact:
        iocage_jails: "{{ ansible_facts.iocage_jails
                          | dict2items
                          | rejectattr('value.properties.notes', 'equalto', 'none')
                          | items2dict }}"

    - name: Create iocage_jails_tags and iocage_jails_started
      vars:
        _keys: "{{ iocage_jails.keys() | list }}"
        _vals: "{{ iocage_jails | dict2items
                                | map(attribute='value.properties.notes')
                                | map('split')
                                | map('map', 'split', '=')
                                | map('community.general.dict') }}"
      ansible.builtin.set_fact:
        iocage_jails_tags: "{{ dict(_keys | zip(_vals)) }}"
        iocage_jails_started: "{{ iocage_jails
                                  | dict2items
                                  | selectattr('value.state', 'eq', 'up')
                                  | map(attribute='key')
                                  | list }}"

- name: Get iocage_jails from inventory.
  when: "iocage_jails_source == 'inventory'"
  block:

    - name: Query inventory plugin.
      delegate_to: localhost
      changed_when: false
      register: out
      ansible.builtin.command:
        cmd: "ansible-inventory -i {{ iocage_jails_inventory_conf }} --list --export"

    - name: Reject jails without iocage_tags
      ansible.builtin.set_fact:
        iocage_jails: "{{ (out.stdout
                          | from_yaml
                          | vbotka.freebsd.clean_unsafe)._meta.hostvars
                          | dict2items
                          | rejectattr('value.iocage_tags', 'undefined')
                          | items2dict }}"

    - name: Create iocage_jails_tags and iocage_jails_started
      vars:
        _keys: "{{ iocage_jails.keys() | list }}"
        _vals: "{{ iocage_jails | dict2items
                                | map(attribute='value.iocage_tags') }}"
      ansible.builtin.set_fact:
        iocage_jails_tags: "{{ dict(_keys | zip(_vals)) }}"
        iocage_jails_started: "{{ iocage_jails
                                  | dict2items
                                  | selectattr('value.iocage_state', 'eq', 'up')
                                  | map(attribute='key')
                                  | list }}"
