---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: Stop and destroy swarms
  vars:
    _query: '[?value.swarm==`{{ item.key }}`].key'
    _swarm_exist: "{{ iocage_jails_tags | dict2items | community.general.json_query(_query) }}"
    _jails_started: "{{ _swarm_exist | intersect(iocage_jails_started) }}"
    cmd_stop: "iocage stop {{ _jails_started | join(' ') }}"
    cmd_destroy: "iocage destroy --force {{ _swarm_exist | join(' ') }}"

  block:

    - name: Get iocage facts
      vbotka.freebsd.iocage:

    - name: Create iocage_jails_tags and iocage_jails_started
      vars:
        _keys: "{{ iocage_jails.keys() | list }}"
        _vals: "{{ iocage_jails | dict2items
                                | map(attribute='value.properties.notes')
                                | map('split')
                                | map('map', 'split', '=')
                                | map('community.general.dict') }}"
      ansible.builtin.set_fact:
        iocage_jails_tags: "{{ dict(_keys | zip(_vals)) }}"
        iocage_jails_started: "{{ iocage_jails
                                  | dict2items
                                  | selectattr('value.state', 'eq', 'up')
                                  | map(attribute='key')
                                  | list }}"

    - name: "Debug iocage_jails, _started, and _tags debug2={{ debug2 }}"
      when: debug2 | bool
      ansible.builtin.debug:
        msg: |
          iocage_jails:
            {{ iocage_jails | to_nice_yaml(indent=2) | indent(2) }}
          iocage_jails_started: {{ iocage_jails_started }}
          iocage_jails_tags:
            {{ iocage_jails_tags | to_nice_yaml(indent=2) | indent(2) }}

    - name: "Debug cmd_stop debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: "{{ cmd_stop }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Stop swarms
      when:
        - not dry_run | d(true) | bool
        - _jails_started | length > 0
      changed_when: false
      register: out
      ansible.builtin.command:
        cmd: "{{ cmd_stop }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Debug stop swarms debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        var: out

    - name: "Debug cmd_destroy debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: "{{ cmd_destroy }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Destroy swarms
      when:
        - not dry_run | d(true) | bool
        - _swarm_exist | length > 0
      changed_when: false
      register: out
      ansible.builtin.command:
        cmd: "{{ cmd_destroy }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Debug destroy swarms debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        var: out
