---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: Create swarms.
  vars:

    _notes_source:
      - "vmm={{ inventory_hostname }}"
      - "{{ properties.notes | d('') }}"
      - "{{ item.value.notes | d('') }}"
      - "{{ item.value.properties.notes | d('') }}"
      - "class={{ item.value.class | d([]) | join(',') }}"
      - "swarm={{ item.key }}"
    _notes: "{{ _notes_source | select | join(' ') }}"

    _properties_source:
      - "{{ properties | d({}) }}"
      - "{{ item.value.properties | d({}) }}"
    _properties_combined: >-
      {{ _properties_source
         | community.general.remove_keys(target=['notes'])
         | select
         | combine(recursive=true) }}
    _properties: >-
      {% for k, v in _properties_combined.items() %}
      {{ k }}={{ v }}
      {% endfor %}
      notes="{{ _notes }}"

    _query: >-
      [?value.swarm==`{{ item.key }}`].key
    _count: "{{ item.value.count - iocage_jails_tags | dict2items | community.general.json_query(_query) | length }}"
    cmd_create_from_template: >-
      iocage create
      --short
      --template {{ item.value.template | d('void') }}
      --count {{ _count }}
      {{ _properties }}
    cmd_clone_from_plugin: >-
      iocage clone
      {{ item.value.plugin | d('void') }}
      --newmac
      --count {{ _count }}
      {{ _properties }}
    cmd_create: |
      {% if 'template' in item.value %}
      {{ cmd_create_from_template }}
      {% elif 'plugin' in item.value %}
      {{ cmd_clone_from_plugin }}
      {% endif %}

  block:

    - name: Get inventory.
      ansible.builtin.import_tasks: get_inventory.yml

    - name: "Debug iocage_jails and iocage_jails_tags debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: |
          iocage_jails:      {{ iocage_jails.keys() | list | sort }}
          iocage_jails_tags: {{ iocage_jails_tags.keys() | list | sort }}

    - name: "Debug iocage_jails and iocage_jails_tags debug2={{ debug2 }}"
      when: debug2 | bool
      ansible.builtin.debug:
        msg: |
          iocage_jails:
            {{ iocage_jails | to_nice_yaml(indent=2) | indent(2) }}
          iocage_jails_tags:
            {{ iocage_jails_tags | to_nice_yaml(indent=2) | indent(2) }}

    - name: "Debug cmd_create debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: "{{ cmd_create }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Create swarms.
      when:
        - not dry_run | bool
        - _count | int > 0
      changed_when: false
      register: out
      ansible.builtin.command:
        cmd: "{{ cmd_create }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Debug create swarms debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        var: out

- name: Start swarms.
  vars:
    _query: '[?value.swarm==`{{ item.key }}`].key'
    _jails: "{{ iocage_jails_tags | dict2items | community.general.json_query(_query) | difference(iocage_jails_started) }}"
    cmd_start: >
      iocage start
      {{ _jails | join(' ') }}

  block:

    - name: Get inventory.
      ansible.builtin.import_tasks: get_inventory.yml

    - name: "Debug iocage_jails and iocage_jails_tags debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: |
          iocage_jails:         {{ iocage_jails.keys() | list | sort }}
          iocage_jails_tags:    {{ iocage_jails_tags.keys() | list | sort }}
          iocage_jails_started: {{ iocage_jails_started | sort }}

    - name: "Debug iocage_jails, _started, and iocage_jails_tags debug2={{ debug2 }}"
      when: debug2 | bool
      ansible.builtin.debug:
        msg: |
          iocage_jails:
            {{ iocage_jails | to_nice_yaml(indent=2) | indent(2) }}
          iocage_jails_started: {{ iocage_jails_started }}
          iocage_jails_tags:
            {{ iocage_jails_tags | to_nice_yaml(indent=2) | indent(2) }}

    - name: "Debug cmd_start debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        msg: "{{ cmd_start }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Start swarms.
      when:
        - not dry_run | bool
        - _jails | length > 0
      changed_when: false
      register: out
      ansible.builtin.command:
        cmd: "{{ cmd_start }}"
      loop: "{{ swarms | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Debug start swarms debug={{ debug }}"
      when: debug | bool
      ansible.builtin.debug:
        var: out
