properties:
  vnet: 'on'
  defaultrouter: 172.16.99.1
  notes: "vmm={{ inventory_hostname }}"

basejails:
  - name: ansible_client
    release: '15.1-RELEASE'
    properties:
      ip4_addr: 'vnet0|172.16.99.197/24'

clones:
  - name: test_151
    clone_from: ansible_client
    properties:
      ip4_addr: 'vnet0|172.16.99.251/24'
  - name: test_152
    clone_from: ansible_client
    properties:
      ip4_addr: 'vnet0|172.16.99.252/24'
  - name: test_153
    clone_from: ansible_client
    properties:
      ip4_addr: 'vnet0|172.16.99.253/24'
