properties:
  notes: "vmm={{ inventory_hostname }}"

clones:
  test-161:
    clone_from: ansible-client
    properties:
      bpf: 1
      vnet: 1
      ip4_addr: 'vnet0|172.16.99.201/24'
      defaultrouter: '172.16.99.1'
      notes: 'swarm=sw_01 alias=test_161'

swarms:
  sw_01:
    count: 3
    template: ansible-client
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1

start: [test-161]
