haproxy_enable: true

haproxy_conf:
  global:
    chroot: /var/empty
    user: haproxy
    group: haproxy
    log: /var/run/log local0 info
    maxconn: 2048
    daemon:
  defaults:
    log: global
    mode: http
    options:
      httplog:
      dontlognull:
    timeouts:
      connect: 5s
      client: 50s
      server: 50s
  frontends:
    http_front:
      bind: "{{ project_hosts.iocage_06.defaultrouter }}:80"
      default_backend: nginx_cluster
  backends:
    nginx_cluster:
      balance: roundrobin
      option httpchk: 'GET /'
      http-check: expect status 200
      servers: "{{ dict(nginx_cluster_keys | zip(nginx_cluster_vals)) }}"
  listens:
    stats:
      bind: "{{ project_hosts.iocage_06.defaultrouter }}:8404"
      mode: http
      stats:
        - enable
        - uri /
        - refresh 5s

nginx_cluster_hosts: "{{ groups['nginx'] | sort }}"
nginx_cluster_keys: "{{ nginx_cluster_hosts
                        | map('extract', hostvars, ['iocage_tags', 'alias'])
                        | list }}"
nginx_cluster_vals_query: "{address: iocage_ip4, port: '80', check: ''}"
nginx_cluster_vals: "{{ nginx_cluster_hosts
                        | map('extract', hostvars)
                        | map('json_query', nginx_cluster_vals_query)
                        | list }}"
