---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Create: Get iocage list of jails."
  register: out_jails
  changed_when: false
  ansible.builtin.command: iocage list --long

- name: "Create: Display iocage_jails fit_debug={{ fit_debug }}"
  when: fit_debug | bool
  ansible.builtin.debug:
    var: fit_iocage_jails

- name: "Create: Create jails."
  register: out
  changed_when: false
  ansible.builtin.command: >-
    iocage create
    --name {{ item.key }}
    --release {{ item.value.release }}
    {% if item.value.pkglist is defined %} --pkglist {{ item.value.pkglist }}{% endif %}
    {% if item.value.properties is defined %}
    {% for k, v in item.value.properties.items() %} {{ k }}={{ v }}{% endfor %}
    {% endif %}
  loop: "{{ fit_templates | dict2items
                          | rejectattr('key', 'in', fit_iocage_templates)
                          | rejectattr('key', 'in', fit_iocage_jails) }}"
  loop_control:
    label: "{{ item.key }} {{ item.value.release }}"

- name: "Create: Debug create templates fit_debug2={{ fit_debug2 }}"
  when: fit_debug2 | bool
  ansible.builtin.debug:
    var: out

# vbotka.freebsd.iocage:
#   state: present
#   name: "{{ item.key }}"
#   release: "{{ item.value.release }}"
#   properties: "{{ item.value.properties | d(omit) }}"
#   pkglist: "{{ item.value.pkglist | d(omit) }}"
