---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Pkg: Install packages."
  register: out
  community.general.pkgng:
    use_globs: false
    jail: "{{ fit_iocage_jails[item.key]['jid'] }}"
    name: "{{ item.value.pkg }}"
    cached: "{{ fit_pkg_cached | bool | d(omit) }}"
  loop: "{{ fit_templates | dict2items
                          | rejectattr('key', 'in', fit_iocage_templates)
                          | selectattr('value.pkg', 'defined') }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Pkg: Debug install packages fit_debug2={{ fit_debug2 }}"
  when: fit_debug2 | bool
  ansible.builtin.debug:
    var: out
