---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Start: Get iocage list of jails."
  register: out_jails
  changed_when: false
  ansible.builtin.command: iocage list --long

- name: "Start: Display iocage_jails fit_debug={{ fit_debug }}"
  when: fit_debug | bool
  ansible.builtin.debug:
    var: fit_iocage_jails

- name: Start jails.
  when: _jails_to_start | length > 0
  vars:
    _jails_started: "{{ fit_iocage_jails | dict2items
                                         | selectattr('value.state', 'eq', 'up')
                                         | map(attribute='key') }}"
    _jails_to_start: "{{ fit_templates | difference(fit_iocage_templates)
                                       | difference(_jails_started) }}"
  block:

    - name: "Start: Display jails to start fit_debug={{ fit_debug }}"
      when: fit_debug | bool
      ansible.builtin.debug:
        var: _jails_to_start

    - name: "Start: Start jails."
      register: out
      changed_when: false
      ansible.builtin.command: >-
        iocage start
        {{ _jails_to_start | join(' ') }}

    - name: "Start: Debug start jails fit_debug2={{ fit_debug2 }}"
      when: fit_debug2 | bool
      ansible.builtin.debug:
        var: out
