log_server_01 ansible_jail_name=1
pkg_repo ansible_jail_name=2
repos ansible_jail_name=3

# log_server_01 ansible_jail_name=log-server-01
# pkg_repo ansible_jail_name=pkg-repo
# repos ansible_jail_name=repos

[vmm_iocage_06]
log_server_01
pkg_repo
repos

[vmm_iocage_06:vars]
ansible_connection=vbotka.freebsd.jailexec
ansible_ssh_user=admin
ansible_jail_host=iocage_06
ansible_jail_privilege_escalation=sudo
