log-server-01 ansible_jail_name=1
pkg-repo ansible_jail_name=2
repos ansible_jail_name=3

[vmm_iocage_06]
log-server-01
pkg-repo
repos

[vmm_iocage_06:vars]
ansible_connection=vbotka.freebsd.jailexec
ansible_ssh_user=admin
ansible_jail_host=iocage_06
ansible_jail_privilege_escalation=sudo
