---
- name: Create jails from iocage plugins.
  hosts: iocage_05

  tasks:

    - name: Create jail.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-server
          alias=log-server"
      ansible.builtin.command: >
        iocage clone
        --newmac
        ansible-pull-syslogng-server
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
