- name: Install packages in jails.
  hosts: swarm_sw_01
  gather_facts: true
    
  tasks:

    - name: Install packages.
      ansible.builtin.import_role:
        name: vbotka.freebsd.postinstall
        tasks_from: packages
