---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Create Ansible client templates.
  hosts: iocage
  environment: "{{ iocage_env | d({}) }}"

  roles:

    - vbotka.freebsd.iocage_template
