---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Clone repos.
  hosts: ansible_repos

  tasks:

    - name: Clone repos.
      ansible.builtin.git:
        repo: "{{ item.value.repo }}"
        dest: "{{ git_daemon_directory }}/{{ item.key }}"
      loop: "{{ repos[inventory_hostname] | dict2items }}"

    - name: Git config safe.directory.
      ansible.builtin.shell:
        cmd: >
          cd {{ git_daemon_directory }}/{{ item.key }};
          git config --global --add safe.directory {{ git_daemon_directory }}/{{ item.key }}
      loop: "{{ repos[inventory_hostname] | dict2items }}"

    - name: Change ownership of repos.
      ansible.builtin.file:
        path: "{{ git_daemon_directory }}/{{ item.key }}"
        state: directory
        owner: git_daemon
        group: git_daemon
        recurse: true
      loop: "{{ repos[inventory_hostname] | dict2items }}"
