---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

# defaults for vbotka.freebsd_haproxy
haproxy_role_version: 1.0.1

haproxy_install: false
haproxy_start: false
haproxy_enable: false
haproxy_debug: false
haproxy_debug2: false
haproxy_backup_conf: false

freebsd_install_method: packages
# freebsd_install_method: ports
freebsd_use_packages: true
freebsd_install_retries: 10
freebsd_install_delay: 5
freebsd_use_globs: false

haproxy_packages:
  - net/haproxy

haproxy_service: haproxy

haproxy_conf_dir: /usr/local/etc
haproxy_conf_file: haproxy.conf
haproxy_conf_owner: root
haproxy_conf_group: wheel
haproxy_conf_mode: '0644'
haproxy_conf_template: default.j2

haproxy_rcconf: {}
haproxy_conf: {}

# EOF
...
