- name: Display inventory.
  hosts: swarm_sw_01

  vars:

    _vars:
      - ansible_jail_host
      - ansible_jail_name

    _properties:
      - host_hostname
      - host_hostuuid

    _cmd: 'whoami; uname -rms'
    _cmd_header: 'who  uname'

  tasks:
    
    - debug:
        msg: |
          inv       name     uuid     jail_host jail_name
          -----------------------------------------------
          {% for h in ansible_play_hosts %}
          {{ h }}  {{ _properties | map('extract', hostvars[h]['iocage_properties']) | join(' ') }} {{ _vars | map('extract', hostvars[h]) | join(' ') }}
          {% endfor %}
      run_once: true

    - shell: "{{ _cmd }}"
      register: out

    - debug:
        msg: |
          inv       {{ _cmd_header }}
          -----------------------------------------
          {% for h in ansible_play_hosts %}
          {{ h }}  {{ hostvars[h].out.stdout_lines | join(' ') }}
          {% endfor %}
      run_once: true
