- name: Display jails in the swarm.
  hosts: swarm_sw_01
    
  tasks:

    - ansible.builtin.command: hostname
      register: out

    - ansible.builtin.debug:
        msg: |
          out.stdout: {{ out.stdout }}
          ansible_host: {{ ansible_host }}
          iocage_hooks: {{ iocage_hooks }}
          iocage_ip4: {{ iocage_ip4 }}
          iocage_tags:
            {{ iocage_tags | to_nice_yaml(2) | indent(2) }}
