- name: Display inventory.
  hosts: swarm_sw_01
    
  tasks:
    
    - debug:
        msg: |
          inv      name     ansible_host  iocage_tags
          ---------------------------------------------------------------------------
          {% for h in ansible_play_hosts %}
          {{ h }} {{ hostvars[h].iocage_properties.host_hostname }} {{ hostvars[h].ansible_host }} {{ hostvars[h].iocage_tags | to_yaml }}
          {%- endfor %}
      run_once: true
