- name: Connect to the group test.
  hosts: test
    
  tasks:

    - command: hostname
      register: out_host
    
    - debug:
        msg: >
          {{ out_host.stdout }}
          {{ iocage_properties.host_hostuuid }}
          {{ iocage_properties.hostid }}

    - command: whoami
      register: out_user
   
    - debug:
        msg: >
          {{ out_host.stdout }}
          {{ out_user.stdout }}
