project:
  www-51:
    notes: alias=www_51
    vmm: iocage_05
    template: ansible-nginx
    class: [nginx]
  www-52:
    notes: alias=www_52
    vmm: iocage_05
    template: ansible-nginx
    class: [nginx]
  www-61:
    notes: alias=www_61
    vmm: iocage_06
    template: ansible-nginx
    class: [nginx]
  www-62:
    notes: alias=www_62
    vmm: iocage_06
    template: ansible-nginx
    class: [nginx]

properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  boot: 1

vmm: "{{ (project | vbotka.freebsd.project).vmm }}"
