- name: Test lookup vbotka.freebsd.galaxy_info
  hosts: iocage

  tasks:
    
    - name: Get the complete meta data dictionary from galaxy.yml
      vars:
        info: "{{ lookup('vbotka.freebsd.galaxy_info', 'all') }}"
      debug:
        msg: |
          type: {{ info | type_debug }}
          info:
            {{ info | to_nice_yaml }}
    
    - name: Get the attributes authors and version.
      vars:
        info: "{{ lookup('vbotka.freebsd.galaxy_info', 'authors', 'version') }}"
      debug:
        msg: |
          type: {{ info | type_debug }}
          authors: {{ info.0 }}
          version: {{ info.1 }}

#   - name: Error. Unknown attribute foo
#     block:
#        - set_fact:
#           foo: "{{ query('vbotka.freebsd.galaxy_info', 'foo') }}"
#        - debug:
#           var: foo
#      rescue:
#        - debug:
#           var: ansible_failed_result
