project:
  repos:
    class: [repos]
    template: ansible_pull_repos
    vmm: iocage_05
  repos-dev:
    class: [repos]
    template: ansible_pull_repos
    vmm: iocage_05

properties:
  bpf: 1
  dhcp: 1
  vnet: 1

vmm_groups: "{{ dict(project | dict2items | groupby('value.vmm')) }}"
vmm: "{{ dict(vmm_groups.keys() | zip(vmm_groups.values() | map('items2dict'))) }}"
