---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: "Debug: Display variables fit_debug={{ fit_debug }}"
  when: fit_debug | bool
  ansible.builtin.debug:
    msg: |
      fit_role_version: {{ fit_role_version }}

      ansible_facts.architecture: {{ ansible_facts.architecture }}
      ansible_facts.os_family: {{ ansible_facts.os_family }}
      ansible_facts.distribution: {{ ansible_facts.distribution }}
      ansible_facts.distribution_major_version: {{ ansible_facts.distribution_major_version }}
      ansible_facts.distribution_version: {{ ansible_facts.distribution_version }}
      ansible_facts.distribution_release: {{ ansible_facts.distribution_release }}
      ansible_facts.python_version: {{ ansible_facts.python_version }}

      fit_sudo: {{ fit_sudo }}
      fit_stop: {{ fit_stop }}
      fit_template: {{ fit_template }}
      fit_pkg_install: {{ fit_pkg_install }}
      fit_pkg_cached: {{ fit_pkg_cached | d('UNDEFINED') }}
      fit_pkg_ignore_osver: {{ fit_pkg_ignore_osver | d('UNDEFINED') }}
      fit_pkg_pkgsite: {{ fit_pkg_pkgsite | d('UNDEFINED') }}

      fit_dir_default:
        {{ fit_dir_default | to_nice_yaml(indent=2) | indent(2) }}
      fit_file_default:
        {{ fit_file_default | to_nice_yaml(indent=2) | indent(2) }}
      fit_dir_options:
        {{ fit_dir_options | to_nice_yaml(indent=2) | indent(2) }}
      fit_file_options:
        {{ fit_file_options | to_nice_yaml(indent=2) | indent(2) }}

      fit_templates:
        {{ fit_templates | to_nice_yaml(indent=2) | indent(2) }}
      fit_iocage_mount: {{ fit_iocage_mount }}
      fit_iocage_templates:
        {{ fit_iocage_templates | to_nice_yaml(indent=2) | indent(2) }}
