---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: "Debug: Display fit_templates fit_debug0={{ fit_debug0 }}"
  when: fit_debug0 | bool
  ansible.builtin.debug:
    msg: |
      fit_templates:
        {{ fit_templates | to_nice_yaml(indent=2) | indent(2) }}
