---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: "Setup: Get iocage list of templates."
  register: out_templates
  changed_when: false
  ansible.builtin.command: iocage list --template --long

- name: "Setup: End role if all templates already created."
  when: fit_templates | difference(fit_iocage_templates) | length == 0
  block:

    - name: "Setup: All templates already created."
      ansible.builtin.debug:
        msg: All templates already created. End role.

    - name: "Setup: End role."
      ansible.builtin.meta: end_role

- name: Set iocage pool mount point.
  block:

    - name: "Setup: Get activated pool."
      register: out_pool
      changed_when: false
      check_mode: false
      ansible.builtin.command: iocage get -p

    - name: "Setup: Debug get activated pool."
      when: fit_debug2 | bool
      ansible.builtin.debug:
        var: out_pool
