fit_pkg_install: true
# fit_pkg_cached: true
# fit_pkg_pkgsite: local

fit_templates:
  ansible-nginx:
    release: 15.1-RELEASE
    pkg:
      - www/nginx-lite
      - lang/python312
      - lang/python
      - lang/python3
    files: "{{ fit_files | dict2items }}"
    properties:
      ip4: disable
      ip6: disable
      ip6_addr: none
      bpf: 1
      dhcp: 1
      vnet: 1
      notes: '"class=nginx alias=ansible_nginx"'

fit_files:
  /usr/local/www/nginx:
    - index.html

fit_file_options:
  /usr/local/www/nginx:
    owner: root
    group: www
    mode: '0755'
  /usr/local/www/nginx/index.yml:
    owner: root
    group: www
    mode: '0644'
