---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Commands: Execute commands."
  changed_when: false
  register: out
  vbotka.freebsd.iocage:
    state: exec
    name: "{{ item.0.key }}"
    cmd: "{{ item.1 }}"
  loop: "{{ fit_templates | dict2items
                          | rejectattr('key', 'in', fit_iocage_templates)
                          | subelements('value.commands', skip_missing=true) }}"
  loop_control:
    label: "{{ item.0.key }} > {{ item.1 }}"

- name: "Commands: Debug execute commands fit_debug2={{ fit_debug2 }}"
  when: fit_debug2 | bool
  ansible.builtin.debug:
    var: out
