---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Create firstboot scripts.
  when: _templates | length > 0
  vars:
    _templates: "{{ fit_templates | dict2items
                                  | rejectattr('key', 'in', fit_iocage_templates)
                                  | subelements('value.firstboot', skip_missing=true) }}"
  block:

    - name: "Firstboot: Create scripts."
      register: out
      ansible.builtin.copy:
        dest: "{{ fit_iocage_mount }}/jails/{{ item.0.key }}/root/etc/rc.d/{{ item.1.key }}"
        content: "{{ item.1.value.content }}"
        mode: '0555'
      loop: "{{ _templates }}"
      loop_control:
        label: "{{ item.0.key }} {{ item.1.key }}"

    - name: "Firstboot: Debug create scripts fit_debug2={{ fit_debug2 }}"
      when: fit_debug2 | bool
      ansible.builtin.debug:
        var: out

    - name: "Firstboot: Touch /firstboot."
      register: out
      ansible.builtin.file:
        path: "{{ fit_iocage_mount }}/jails/{{ item.0.key }}/root/firstboot"
        state: touch
        mode: '0600'
        modification_time: preserve
        access_time: preserve
      loop: "{{ _templates }}"
      loop_control:
        label: "{{ item.0.key }}"

    - name: "Firstboot: Debug touch /firstboot fit_debug2={{ fit_debug2 }}"
      when: fit_debug2 | bool
      ansible.builtin.debug:
        var: out
