---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Setup: Get iocage list of templates."
  register: out_templates
  changed_when: false
  ansible.builtin.command: iocage list --template --long

- name: "Setup: End host if all templates already created."
  when: fit_templates | difference(fit_iocage_templates) | length == 0
  block:

    - name: "Setup: All templates already created."
      ansible.builtin.debug:
        msg: All templates already created. End host.

    - name: "Setup: End host."
      ansible.builtin.meta: end_host

- name: "Setup: Set iocage pool mount point."
  block:

    - name: "Setup: Get activated pool."  # noqa: risky-shell-pipe
      register: out_pool
      changed_when: false
      check_mode: false
      ansible.builtin.shell: >
        zfs list -H -o name |
        grep '/iocage$' |
        cut -d'/' -f1

    - name: "Debug: Display get activated pool."
      when: fit_debug2 | bool
      ansible.builtin.debug:
        var: out_pool
