- name: Test module vbotka.freebsd.service. Get running jails sendmail rcvar(s).
  hosts: state_up
    
  tasks:

    - name: Get sendmail rcvar(s).
      vbotka.freebsd.service:
        script: sendmail
        command: rcvar
      register: out

    - ansible.builtin.debug:
        var: out.rcvar
