# -*- coding: utf-8 -*-

from __future__ import annotations
from ansible.errors import AnsibleFilterError

DOCUMENTATION = r"""
name: ast_to_haproxy
short_description: Convert an AST structure to HAProxy configuration format
version_added: "1.0.6"
author:
  - Vladimir Botka (@vbotka)
description:
  - Transforms an Abstract Syntax Tree (AST) dictionary or sequence—such as
    the intermediate output of C(vbotka.freebsd.dict_to_ast)—into a valid
    native HAProxy configuration string (C(haproxy.cfg)).
  - Handles plural block groupings (C(frontends), C(backends), C(listens)) by
    expanding them into singular section declarations.
  - Automatically formats grouped directives such as C(options), C(timeouts),
    C(acls), and C(use_backends) into native single-line directives.
  - Converts boolean indicators to bare HAProxy flags (e.g., C(daemon True)
    becomes C(daemon), C(check True) becomes C(check)).
positional: _input
options:
  _input:
    description:
      - The AST data structure representing the HAProxy configuration.
      - Can be a mapping (root node) or a sequence of section nodes.
    type: raw
    required: true
  indent:
    description:
      - Number of spaces used to indent directives inside section blocks.
    type: int
    default: 4
requirements:
  - Python >= 3.9
notes:
  - Often paired in a pipeline with C(vbotka.freebsd.dict_to_ast).
"""

EXAMPLES = r"""
# Pipeline conversion from YAML/dict via dict_to_ast to native haproxy.cfg
- name: Render HAProxy configuration from structured data
  ansible.builtin.debug:
    msg: "{{ haproxy_config_data | vbotka.freebsd.dict_to_ast | vbotka.freebsd.ast_to_haproxy }}"

# Write rendered HAProxy configuration with custom 2-space indentation
- name: Deploy HAProxy configuration file
  ansible.builtin.copy:
    content: "{{ haproxy_ast | vbotka.freebsd.ast_to_haproxy(indent=2) }}"
    dest: /usr/local/etc/haproxy.conf
    owner: root
    group: wheel
    mode: '0644'
"""

RETURN = r"""
_value:
  description:
    - Syntactically valid HAProxy configuration text ready to write to disk.
  type: str
  returned: always
"""

from collections.abc import Mapping, Sequence


class HAProxyGenerator:
    """
    Serializes an AST generated by dict_to_ast into valid HAProxy configuration.
    """

    KNOWN_OPTIONS = {
        "httplog",
        "dontlognull",
        "http-server-close",
        "forwardfor",
        "redispatch",
        "tcplog",
        "ssl-hello-chk",
    }

    KNOWN_TIMEOUTS = {
        "connect",
        "client",
        "server",
        "queue",
        "http-request",
        "http-keep-alive",
        "check",
    }

    PLURAL_SECTIONS = {
        "frontends": "frontend",
        "backends": "backend",
        "listens": "listen",
    }

    def __init__(self, indent=4):
        self.indent_str = " " * indent

    def visit(self, node):
        if isinstance(node, Sequence) and not isinstance(node, (str, bytes)):
            return self.visit_sequence(node)

        if not isinstance(node, Mapping):
            return str(node)

        # Handle top-level plural containers if present as a single node
        directive = self._get_node_name(node)
        if directive in self.PLURAL_SECTIONS:
            return self._render_plural_section_node(node)

        body = self._get_node_body(node)
        if body is not None:
            return self.visit_section(node)

        return self.visit_directive(node)

    def visit_sequence(self, nodes):
        rendered = []
        for item in nodes:
            out = self.visit(item)
            if out:
                rendered.append(out)
        return "\n\n".join(rendered) + ("\n" if rendered else "")

    def _get_node_name(self, node):
        return node.get("directive") or node.get("name") or node.get("section_type")

    def _get_node_args(self, node):
        for key in ("args", "param", "value"):
            if key in node and node[key] is not None:
                val = node[key]
                if isinstance(val, (str, bytes)):
                    return [val.strip()]
                if isinstance(val, Sequence):
                    return [str(v).strip() for v in val if str(v).strip() != ""]
                return [str(val).strip()]
        return []

    def _get_node_body(self, node):
        for key in ("block", "body", "children"):
            if key in node and isinstance(node[key], Sequence) and not isinstance(node[key], (str, bytes)):
                return node[key]
        return None

    def _render_plural_section_node(self, node):
        """Unpacks containers like 'frontends' or 'backends' into separate sections."""
        directive = self._get_node_name(node)
        singular = self.PLURAL_SECTIONS[directive]
        body = self._get_node_body(node) or []
        sections = []

        for item in body:
            if not isinstance(item, Mapping):
                continue
            sec_name = self._get_node_name(item)
            sec_body = self._get_node_body(item) or []
            # Synthesize section node
            sec_node = {
                "directive": singular,
                "args": [sec_name] if sec_name else [],
                "block": sec_body,
            }
            rendered = self.visit_section(sec_node)
            if rendered:
                sections.append(rendered)

        return "\n\n".join(sections)

    def visit_section(self, node):
        directive = self._get_node_name(node)
        if directive in self.PLURAL_SECTIONS:
            return self._render_plural_section_node(node)

        args = self._get_node_args(node)
        header_parts = [directive]
        if args:
            header_parts.extend(args)
        header = " ".join(header_parts).strip()

        lines = [header]
        body = self._get_node_body(node) or []

        for item in body:
            if not isinstance(item, Mapping):
                continue

            item_dir = self._get_node_name(item)
            item_body = self._get_node_body(item)

            # 1. Server groups (e.g. servers: web1: ...)
            if item_dir == "servers" and item_body:
                for s_node in item_body:
                    lines.append("{0}{1}".format(self.indent_str, self._render_server_node(s_node)))
                continue

            # 2. ACL groups (e.g. acls: is_api: ...)
            if item_dir == "acls" and item_body:
                for acl_node in item_body:
                    lines.append("{0}{1}".format(self.indent_str, self._render_acl_node(acl_node)))
                continue

            # 3. Timeout groups
            if item_dir == "timeouts" and item_body:
                for t_node in item_body:
                    lines.append("{0}{1}".format(self.indent_str, self._render_timeout_node(t_node)))
                continue

            # 4. Option groups
            if item_dir == "options" and item_body:
                for o_node in item_body:
                    lines.append("{0}{1}".format(self.indent_str, self._render_option_node(o_node)))
                continue

            # 5. use_backends group (list of backend/condition dicts)
            if item_dir in ("use_backends", "use_backend") and item_body:
                for ub_node in item_body:
                    line = self._render_use_backend_node(ub_node)
                    if line:
                        lines.append("{0}{1}".format(self.indent_str, line))
                continue

            # 6. Standalone directive lines
            line = self.visit_directive(item)
            if line:
                lines.append("{0}{1}".format(self.indent_str, line))

        return "\n".join(lines)

    def visit_directive(self, node):
        directive = self._get_node_name(node)
        if not directive:
            return None

        args = self._get_node_args(node)

        # Boolean directives: strip literal 'True' arguments
        if args == ["True"] or args == ["true"]:
            args = []
        elif args == ["False"] or args == ["false"]:
            return None

        # Auto-prefix options and timeouts if bare
        if directive in self.KNOWN_OPTIONS:
            return "option {0}".format(directive)

        if directive in self.KNOWN_TIMEOUTS:
            arg_str = " ".join(args)
            return "timeout {0} {1}".format(directive, arg_str).strip()

        # Handle ACLs defined at section level (name: is_api, args: [...])
        if directive.startswith("is_") or "path_beg" in args or "path_end" in args or "hdr" in args:
            arg_str = " ".join(args)
            return "acl {0} {1}".format(directive, arg_str).strip()

        if args:
            return "{0} {1}".format(directive, " ".join(args)).strip()

        return directive

    def _render_server_node(self, node):
        s_name = self._get_node_name(node)
        body = self._get_node_body(node) or []
        addr = ""
        check = False
        extra = []

        for prop in body:
            p_name = self._get_node_name(prop)
            p_args = self._get_node_args(prop)
            if p_name in ("address", "addr"):
                addr = p_args[0] if p_args else ""
            elif p_name == "check":
                if not p_args or p_args[0].lower() == "true":
                    check = True
            else:
                if p_args and p_args[0].lower() not in ("true", "false"):
                    extra.append("{0} {1}".format(p_name, " ".join(p_args)))
                elif not p_args or p_args[0].lower() == "true":
                    extra.append(p_name)

        parts = ["server", s_name, addr]
        if check:
            parts.append("check")
        if extra:
            parts.extend(extra)

        return " ".join(parts).strip()

    def _render_acl_node(self, node):
        name = self._get_node_name(node)
        args = self._get_node_args(node)
        return "acl {0} {1}".format(name, " ".join(args)).strip()

    def _render_timeout_node(self, node):
        name = self._get_node_name(node)
        args = self._get_node_args(node)
        return "timeout {0} {1}".format(name, " ".join(args)).strip()

    def _render_option_node(self, node):
        name = self._get_node_name(node)
        args = self._get_node_args(node)
        if args and args[0].lower() not in ("true", "false"):
            return "option {0} {1}".format(name, " ".join(args)).strip()
        return "option {0}".format(name).strip()

    def _render_use_backend_node(self, node):
        body = self._get_node_body(node) or []
        backend = ""
        condition = ""

        for prop in body:
            p_name = self._get_node_name(prop)
            p_args = self._get_node_args(prop)
            if p_name == "backend":
                backend = p_args[0] if p_args else ""
            elif p_name == "condition":
                condition = " ".join(p_args)

        if backend:
            return "use_backend {0} {1}".format(backend, condition).strip()
        return None


def ast_to_haproxy(data, indent=4):
    if not isinstance(data, (Mapping, Sequence)) or isinstance(data, (str, bytes)):
        raise AnsibleFilterError(
            "ast_to_haproxy expects a Sequence or Mapping, got {0}".format(type(data).__name__)
        )

    generator = HAProxyGenerator(indent=indent)
    return generator.visit(data)


class FilterModule(object):
    def filters(self):
        return {
            "ast_to_haproxy": ast_to_haproxy,
        }
