---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

# tasks for vbotka.freebsd_nginx
- name: Import debug.yml
  when: nginx_debug | bool
  tags: [nginx_debug, always]
  ansible.builtin.import_tasks: debug.yml

- name: Import packages.yml
  when: nginx_install | bool
  tags: nginx_packages
  ansible.builtin.import_tasks: packages.yml

- name: Import files.yml
  tags: nginx_files
  ansible.builtin.import_tasks: files.yml

- name: Import conf.yml
  tags: nginx_conf
  ansible.builtin.import_tasks: conf.yml

- name: Import service.yml
  tags: nginx_service
  ansible.builtin.import_tasks: service.yml

# EOF
...
