vmm_clones: "{{ (project_clones | vbotka.freebsd.project).vmm }}"
project_clones: "{{ dict(clones.keys()
                         | zip(clones.values()
                               | map('combine', {'vmm': inventory_hostname}))) }}"
