---
- name: Create iocage templates.
  hosts: iocage
  gather_facts: false

  tasks:

    - command: "ls -1 {{ playbook_dir }}/conf.d"
      register:
        conf_d: _task.result.stdout_lines
      delegate_to: localhost

    - debug:
        var: conf_d

    - include_tasks: tasks/create_template.yml
      loop: "{{ conf_d }}"
      loop_control:
        loop_var: oitem
