project_template: ansible-client

project:
  logserv_1:
    vmm: iocage_05
    class: [log-server]
  http_1:
    vmm: iocage_05
    class: [http, log-client]
  db_1:
    vmm: iocage_05
    class: [db, log-client]
  logserv_2:
    vmm: iocage_06
    class: [log-server]
  http_2:
    vmm: iocage_06
    class: [http, log-client]
  db_2:
    vmm: iocage_06
    class: [db, log-client]

vmm: "{{ (project | vbotka.freebsd.project).vmm }}"
class: "{{ (project | vbotka.freebsd.project).class }}"

properties:
  bpf: 1
  dhcp: 1
  vnet: 1
