fit_templates:
  ansible-init:
    release: 15.0-RELEASE
    pkglist: /tmp/ansible/ansible_init/pkgs.json
    cron: "{{ fit_cron | dict2items }}"
    files: "{{ fit_files | dict2items }}"
    file_lines: "{{ fit_file_lines | dict2items }}"
    firstboot: "{{ fit_firstboot | dict2items }}"
    rcconf: "{{ fit_rcconf | dict2items }}"
    properties:
      ip4: disable
      ip6: disable
      ip6_addr: none
      bpf: 1
      dhcp: 1
      vnet: 1
      notes: '"class=init alias=ansible_init"'

fit_firstboot:
  ansible_init:
    content: |
      #!/bin/sh
      #
      # PROVIDE: ansible_init
      # REQUIRE: FILESYSTEMS NETWORKING
      # KEYWORD: firstboot

      . /etc/rc.subr

      name="ansible_init"
      desc="Firstboot ansible-pull initialization"
      rcvar="ansible_init_enable"

      # Default configuration settings
      : ${ansible_init_enable:="NO"}
      : ${ansible_init_host:="http://localhost"}
      : ${ansible_init_repo:="ansible-conf-init"}
      : ${ansible_init_dest:="/root"}
      : ${ansible_init_vars:="/root/ansible-vars"}
      : ${ansible_init_playbook:="pb-init.yml"}

      # Define the command to run
      command="/usr/local/bin/ansible-pull"

      # Pass the environment variables
      ansible_init_env="\
          PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin \
          LANG=en_US.UTF-8 \
          LC_ALL=en_US.UTF-8"

      # Construct the arguments
      load_rc_config $name
      command_args="\
          -i hosts \
          -U ${ansible_init_host}/${ansible_init_repo} \
          -d ${ansible_init_dest}/${ansible_init_repo} \
          -e 'ai_vars=${ansible_init_vars}' \
          -e 'ai_pull_mode=true' \
          ${ansible_init_playbook}"

      run_rc_command "$1"

fit_rcconf:
  ansible_init_enable: "YES"
  ansible_init_host: "git://{{ project_hosts[inventory_hostname]['repos'] }}"

fit_cron:
  /etc/cron.d/at:
    - name: Run atrun execution daemon in 1 minute intervals.
      minute: '*/1'
      hour: '*'
      day: '*'
      month: '*'
      weekday: '*'
      user: root
      job: /usr/libexec/atrun
      exclusive: true

fit_files:
  /root/ansible-vars:
    - project-hosts.yml
    - hello-world.txt

fit_file_lines:
  /root/.profile:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

fit_file_options:
  /root/ansible-vars:
    owner: root
    group: wheel
    mode: '0750'
  /root/.profile:
    assignment_operator: '='
    owner: root
    group: wheel
    mode: '0644'
