# The project keys are jails aliases.
project:
  logserv:
    class: [logserv]
    plugin: ansible-syslogng
    vmm: iocage_05
  foo:
    class: [logclient]
    plugin: ansible-syslogng
    vmm: iocage_05
  bar:
    class: [logclient]
    plugin: ansible-syslogng
    vmm: iocage_05

plugins:
  ansible-syslogng:
    git: https://github.com/vbotka/iocage-plugins
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1

# Jail properties.
properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  type: jail

# Declare vmm. Dictionary of iocage hosts.
vmm_groups: "{{ dict(project | dict2items | groupby('value.vmm')) }}"
vmm: "{{ dict(vmm_groups.keys() | zip(vmm_groups.values() | map('items2dict'))) }}"
