project:
  log-server:
    notes: alias=log_server
    vmm: iocage_05
    template: ansible-init
    class: [log-server]
    custom_facts: class.fact.j2
    properties:
      defaultrouter: "{{ project_hosts[inventory_hostname]['defaultrouter'] }}"
      ip4_addr: "vnet0|{{ project_hosts[inventory_hostname]['log_server'] }}/24"
      vnet: 1
      boot: 1
  www-01:
    notes: alias=www_01
    vmm: iocage_05
    template: ansible-init
    class: [log-client]
    custom_facts: class.fact.j2
  www-02:
    notes: alias=www_02
    vmm: iocage_05
    template: ansible-init
    class: [log-client]
    custom_facts: class.fact.j2

properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  boot: 1

vmm_groups: "{{ dict(project | dict2items | groupby('value.vmm')) }}"
vmm: "{{ dict(vmm_groups.keys() | zip(vmm_groups.values() | map('items2dict'))) }}"
