# This play is not idempotent! New jails are created each time this play runs.
- name: Create and start swarms (not idempotent!).
  hosts: iocage
  environment: "{{ iocage_env | d({}) }}"

  tasks:

    - name: Create swarms.
      block:

        - name: Create swarms.
          register: out_swarms
          ansible.builtin.command:
            cmd: >-
              iocage create
              --short
              --count {{ item.value.count }}
              --template {{ item.value.template }}
              {{ properties }}
          loop: "{{ swarms | dict2items }}"

        - name: Debug create swarms.
          when: debug | d(false) | bool
          ansible.builtin.debug:
            msg: |
              cmd:
                {{ item.cmd }}
              stdout:
                {{ item.stdout }}
          loop: "{{ out_swarms.results }}"
          loop_control:
            label: "{{ item.item.key }}"

        - name: Debug create swarms.
          when: debug2 | d(false) | bool
          ansible.builtin.debug:
            var: out_swarms

    - name: Create notes.
      block:

        - name: Create notes.
          register: out_notes
          vars:
            jail_name: "{{ item.1 | split | first }}"
            iocage_tags: >-
              vmm={{ inventory_hostname}}
              project={{ project }}
              swarm={{ item.0.item.key }}
              alias={{ alias[idx] }}
          ansible.builtin.command:
            cmd: >-
              iocage set
              notes="{{ iocage_tags }}"
              {{ jail_name }}
          loop: "{{ out_swarms.results | subelements('stdout_lines') }}"
          loop_control:
            index_var: idx
            label: "{{ jail_name }} {{ iocage_tags }}"

        - name: Debug create notes.
          when: debug | d(false) | bool
          ansible.builtin.debug:
            msg: |
              cmd: {{ item.cmd }}
              {{ item.stdout }}
          loop: "{{ out_notes.results }}"
          loop_control:
            label: "{{ item.idx }}"
    
        - name: Debug create notes.
          when: debug2 | d(false) | bool
          ansible.builtin.debug:
            var: out_notes

    - name: Start the jails.
      vars:
        jail_names: "{{ out_swarms.results
                        | map(attribute='stdout_lines')
                        | flatten
                        | map('split')
                        | map('first') }}"
      block:

        - name: Start jails.
          register: out_start
          ansible.builtin.command:
            cmd: >-
              iocage start {{ jail_names | join(' ') }}

        - name: Debug start jails.
          when: debug | d(false) | bool
          ansible.builtin.debug:
            msg: |
              cmd: {{ out_start.cmd }}
              {{ out_start.stdout }}
    
        - name: Debug start jails.
          when: debug2 | d(false) | bool
          ansible.builtin.debug:
            var: out_start
