- name: Destroy swarms.
  hosts: iocage
  environment: "{{ iocage_env | d({}) }}"

  tasks:

    - name: Stop and destroy swarms.
      vars:
        group: "swarm_{{ item }}"
        uuids: "{{ groups[group] | d([])
                   | map('extract', hostvars, ['iocage_properties', 'host_hostuuid']) }}"
      block:

        - name: Display commands.
          when: debug | d(false) | bool
          register: out
          ansible.builtin.debug:
             msg: "iocage stop {{ uuids | join(' ') }}"
          loop: "{{ swarms.keys() | list }}"

        - name: Stop swarms.
          when: uuids | length > 0
          register: out
          ansible.builtin.command: "iocage stop {{ uuids | join(' ') }}"
          loop: "{{ swarms.keys() | list }}"

        - name: Debug stop swarms.
          when: debug | d(false) | bool
          ansible.builtin.debug:
            var: out

        - name: Destroy swarms.
          when: uuids | length > 0
          register: out
          ansible.builtin.command: "iocage destroy -f {{ uuids | join(' ') }}"
          loop: "{{ swarms.keys() | list }}"

        - name: Debug destroy swarms.
          when: debug | d(false) | bool
          ansible.builtin.debug:
            var: out
