freebsd_iocage_install: false  # The packages are installed in the playbook pb-packages.yml

freebsd_iocage_mount: /zroot/iocage
freebsd_iocage_pool: zroot
freebsd_iocage_pool_mount: /zroot

freebsd_iocage_sanity_zfs_pool_active: true
