fzfs_enable: true

fzfs_pools:
  zroot:
    vdevs:
      - disks: [/dev/nda0p5]

fzfs_manage:
  - name: zroot/export
    state: present
    extra_zfs_properties:
      compression: 'lz4'
      mountpoint: /export
  - name: zroot/ports
    state: present
    extra_zfs_properties:
      compression: 'lz4'
      mountpoint: /usr/ports
  - name: zroot/src
    state: present
    extra_zfs_properties:
      compression: 'lz4'
      mountpoint: /usr/src
  - name: zroot/obj
    state: present
    extra_zfs_properties:
      compression: 'lz4'
      mountpoint: /usr/obj
  - name: zroot/poudriere
    state: present
    extra_zfs_properties:
      compression: 'lz4'
      mountpoint: /usr/local/poudriere
