plugin: ansible.builtin.constructed

keyed_groups:
  - prefix: project
    key: iocage_tags.project
  - prefix: swarm
    key: iocage_tags.swarm
  - prefix: state
    key: iocage_state
  - prefix: vmm
    key: iocage_tags.vmm
