project:
  baz:
    vmm: iocage_06
    template: ansible-init
    class: [test]
    custom_facts: class.fact.j2
  qux:
    vmm: iocage_06
    template: ansible-init
    class: [test]
    custom_facts: class.fact.j2

properties:
  ip4: disable
  ip6: disable
  ip6_addr: none
  bpf: 1
  dhcp: 1
  vnet: 1
  boot: 1

vmm_groups: "{{ dict(project | dict2items | groupby('value.vmm')) }}"
vmm: "{{ dict(vmm_groups.keys() | zip(vmm_groups.values() | map('items2dict'))) }}"
