enabled_plugins:
  - ansible-pull-test

plugins:
  ansible-pull-test:
    git: https://github.com/vbotka/iocage-plugins
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1

# jail properties
properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  type: jail
