freebsd_iocage_pool: zroot
freebsd_iocage_pool_mount: /zroot
freebsd_iocage_mount: /zroot/iocage

templates:
  ansible_client:
    release: 15.0-RELEASE
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1
      defaultrouter: 10.10.99.1
    dhclient: "{{ act_dhclient | dict2items }}"
    rcconf: "{{ act_rcconf | dict2items }}"
    # pkglist: /tmp/ansible/ansible_client/pkgs.json

# pkg
act_pkg_install: true
act_pkg:
  - python311
  - sudo

# ansible client template defaults
act_user: admin
act_pk: pk_admins.txt
act_sudo: true
act_rcconf:
  iocage_enable: "YES"
  sshd_enable: "YES"
act_dhclient:
  dhclient-exit-hooks: |
    case "$reason" in
        "BOUND"|"REBIND"|"REBOOT"|"RENEW")
        echo $new_ip_address > /var/db/dhclient-hook.address.$interface
        ;;
    esac

clones:
  test_151: {clone_from: ansible_client}
  test_152: {clone_from: ansible_client}
  test_153: {clone_from: ansible_client}
start: "{{ clones.keys() }}"
swarms: {}

# clones default properties
properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  defaultrouter: 10.10.99.1
  notes: "vmm={{ inventory_hostname }}"
