---
- name: Create jails from iocage plugins.
  hosts: iocage_05

  tasks:

    - name: Create jail.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-client"
      ansible.builtin.command: >
        iocage clone
        --name "{{ item }}"
        --newmac
        ansible-pull-syslogng-client
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
      loop: "{{ log_clients }}"
