---
- name: Create jails from iocage templates.
  hosts: iocage_05

  tasks:

    - name: Create jail.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-server"
      ansible.builtin.command: >
        iocage create
        --name log-server
        --template ansible_syslogng_server
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
