---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Get already fetched plugins.
  changed_when: false
  check_mode: false
  register: out
  ansible.builtin.command: 'iocage list --plugins'

- name: "Debug fetched plugins debug={{ debug }}"
  when: debug | bool
  ansible.builtin.debug:
    msg: |
      iocage_plugins:
        {{ iocage_plugins | to_nice_yaml }}
      plugins:
        {{ plugins | to_nice_yaml }}
