[jail_hosts]
iocage_05 ansible_connection=ssh ansible_user=admin

[jails]
test_151 ansible_jail_name=4
# cb040eb9 ansible_jail_name=1
# dd911c4f ansible_jail_name=2
# f20ab29e ansible_jail_name=3

[jails:vars]
ansible_user=admin
ansible_jail_host=iocage_05
ansible_connection=vbotka.freebsd.jailexec
ansible_jail_privilege_escalation=sudo
ansible_python_interpreter=auto_silent
