- name: Test from_ucl filter.
  hosts: localhost
  connection: local

  vars:

    pkg_repo_config:
      FreeBSD:
        url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly"
        mirror_type: "srv"
        signature_type: "fingerprints"
        fingerprints: "/usr/share/keys/pkg"
        enabled: true
        priority: 100
    pkg_repo_ucl: |
      {{ pkg_repo_config | vbotka.freebsd.to_ucl }}

  tasks:

    - debug:
        msg: |
          {{ pkg_repo_ucl | vbotka.freebsd.from_ucl }}
