---
- name: Create jails from iocage plugins.
  hosts: iocage_05

  tasks:

    - name: Create jail.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=ansible-pull"
      ansible.builtin.command: >
        iocage clone
        --name test
        --newmac
        ansible-pull-test
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
