freebsd_iocage_pool: zroot
freebsd_iocage_pool_mount: /zroot
freebsd_iocage_mount: /zroot/iocage

templates:
  ansible-client:
    release: 15.1-RELEASE
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1
    dhclient: "{{ act_dhclient | dict2items }}"
    rcconf: "{{ act_rcconf | dict2items }}"
    pkglist: /tmp/ansible/ansible-client/pkgs.json

# ansible client template vars
act_user: admin
act_pk: pk_admins.txt
act_sudo: true
act_rcconf:
  sshd_enable: "YES"
act_dhclient: {}

clones:
  test-161:
    clone_from: ansible-client
    properties:
      ip4_addr: 'vnet0|172.16.99.161/24'
  test-162:
    clone_from: ansible-client
    properties:
      ip4_addr: 'vnet0|172.16.99.162/24'
  test-163:
    clone_from: ansible-client
    properties:
      ip4_addr: 'vnet0|172.16.99.163/24'

# clones default properties
properties:
  bpf: 1
  defaultrouter: 172.16.99.1
  notes: "vmm={{ inventory_hostname }}"

start: "{{ clones.keys() }}"

vmm_clones: "{{ (project_clones | vbotka.freebsd.project).vmm }}"
project_clones: "{{ dict(clones.keys()
                         | zip(clones.values()
                               | map('combine', {'vmm': inventory_hostname}))) }}"
