- name: Test empty iocage notes.
  hosts: iocage_06

  tasks:

    - command: iocage get notes test_5
      register: out

    - debug:
        msg: |
          out.stdout: {{ out.stdout }}
          out.stdout type: {{ out.stdout | type_debug }}
