enabled_plugins:
  - ansible-pull-syslogng-client

plugins:
  ansible-pull-syslogng-client:
    git: https://github.com/vbotka/iocage-plugins
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1

# jail properties
properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  type: jail

# log clients' aliases
log_clients:
  - foo
  - bar
