plugin: ansible.builtin.constructed
groups:
    test: inventory_hostname.startswith('test')
keyed_groups:
  - prefix: distro
    key: iocage_release
  - prefix: state
    key: iocage_state
  - prefix: vmm
    key: iocage_tags.vmm
