freebsd_iocage_pool: zroot
freebsd_iocage_pool_mount: /zroot
freebsd_iocage_mount: /zroot/iocage

templates:
  ansible-client:
    release: 14.3-RELEASE
    properties:
      bpf: 'on'
      dhcp: 'on'
      vnet: 'on'
    dhclient: "{{ act_dhclient | dict2items }}"
    rcconf: "{{ act_rcconf | dict2items }}"
    pkglist: /tmp/ansible/ansible-client/pkgs.json

# ansible client template defaults
act_user: admin
act_pk: pk_admins.txt
act_sudo: true
act_rcconf:
  iocage_enable: "YES"
  sshd_enable: "YES"
act_dhclient: {}

clones:
  test-121:
    clone_from: ansible-client
    properties:
      ip4_addr: 'em0|10.1.0.121/24'
  test-122:
    clone_from: ansible-client
    properties:
      ip4_addr: 'em0|10.1.0.122/24'
  test-123:
    clone_from: ansible-client
    properties:
      ip4_addr: 'em0|10.1.0.123/24'

# clones default properties
properties:
  notes: "vmm={{ inventory_hostname }}"

start: "{{ clones.keys() }}"

iocage_env:
  CRYPTOGRAPHY_OPENSSL_NO_LEGACY: 1
