- name: Test module vbotka.freebsd.service. Start smartd.
  hosts: iocage

  vars:

    debug: false
    start_cmd_enable: "{{ rcvar.rcvar.smartd_enable == 'YES' }}"
    start_cmd: "{{ start_cmd_enable | ternary('start', 'onestart') }}"
    
  tasks:

    - name: Get smartd rcvar.
      register: rcvar
      vbotka.freebsd.service:
        script: smartd
        command: rcvar

    - ansible.builtin.debug:
        msg: |
          rcvar.rcvar: {{ rcvar.rcvar }}
          rcvar.rcvar.smartd_enable: {{ rcvar.rcvar.smartd_enable }}
          start_cmd_enable: {{ start_cmd_enable }}
          start_cmd: {{ start_cmd }}
      when: debug | bool

      # 500ms is enough to complete 'service smartd (one)start'.
      # The status before and after the command are different and dictionary status is returned.
      # As a result, the module returns 'changed: true'
    - name: Start smartd. By default wait 500ms to complete the command.
      register: out
      vbotka.freebsd.service:
        script: smartd
        command: "{{ start_cmd }}"

    - ansible.builtin.debug:
        var: out

    - name: Get smartd status.
      register: out
      vbotka.freebsd.service:
        script: smartd
        command: status

    - ansible.builtin.debug:
        var: out

    - name: Stop smartd. By default wait 500ms to complete the command.
      register: out
      vbotka.freebsd.service:
        script: smartd
        command: stop

    - ansible.builtin.debug:
        var: out

      # 200ms is not enough to complete 'service smartd (one)start'.
      # The status before and after the command do not change and are not returned.
      # As a result, the module returns 'changed: false'
      # The service smartd is started. See the next status.
    - name: Start smartd. Wait 200ms to complete the command.
      register: out
      vbotka.freebsd.service:
        script: smartd
        command: "{{ start_cmd }}"
        wait: 0.2

    - ansible.builtin.debug:
        var: out

    - name: Get smartd status.

      register: out
      vbotka.freebsd.service:
        script: smartd
        command: status

    - ansible.builtin.debug:
        var: out
