enabled_plugins:
  - ansible-pull-syslogng-client

plugins:
  ansible-pull-syslogng-client:
    git: https://github.com/vbotka/iocage-plugins-devel
    branch: main
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1
      boot: 0

# jail properties
properties:
  bpf: 1
  dhcp: 1
  vnet: 1
  type: jail
  boot: 1

# log clients' aliases
log_clients:
  - foo
  - bar
