---
- name: Create jails from iocage plugins.
  hosts: iocage_05

  tasks:

    - name: Create syslog-ng server.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-server"
      ansible.builtin.command: >
        iocage clone
        --name log-server
        --newmac
        ansible-pull-syslogng-server
        {{ log_server_properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}

    - name: Create syslog-ng clients.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-client"
      ansible.builtin.command: >
        iocage clone
        --name {{ item }}
        --newmac
        ansible-pull-syslogng-client
        {{ log_client_properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
      loop: "{{ log_clients }}"
