enabled_plugins:
  - ansible-pull-init

classes:
  - foo
  - bar

plugins:
  ansible-pull-init:
    git: https://github.com/vbotka/iocage-plugins-devel
    branch: main
    properties:
      bpf: 1
      dhcp: 1
      vnet: 1
      boot: 0
      notes: "class={{ classes | join(',') }}"
