---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Create: Create templates."
  register: out
  vbotka.freebsd.iocage:
    state: present
    name: "{{ item.key }}"
    release: "{{ item.value.release }}"
    properties: "{{ item.value.properties | d(omit) }}"
    pkglist: "{{ item.value.pkglist | d(omit) }}"
  loop: "{{ fit_templates | dict2items
                          | rejectattr('key', 'in', fit_iocage_templates) }}"
  loop_control:
    label: "{{ item.key }} {{ item.value.release }}"

- name: "Create: Debug create templates fit_debug2={{ fit_debug2 }}"
  when: fit_debug2 | bool
  ansible.builtin.debug:
    var: out
