---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Debug: Display variables fit_debug={{ fit_debug }}"
  when: fit_debug | bool
  ansible.builtin.debug:
    msg: |
      fit_pkg_install: {{ fit_pkg_install }}
      fit_sudo: {{ fit_sudo }}
      fit_stop: {{ fit_stop }}
      fit_template: {{ fit_template }}

      fit_templates:
        {{ fit_templates | to_nice_yaml(indent=2) | indent(2) }}
      fit_iocage_templates:
        {{ fit_iocage_templates | to_nice_yaml(indent=2) | indent(2) }}
