---
- name: Create jails from iocage templates.
  hosts: iocage_05

  tasks:

    - name: Create log_server
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-server
          alias=log_server"
      ansible.builtin.command: >
        iocage create
        --name log-server
        --template ansible-syslogng-server
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
