---
- name: Stop and convert ansible-syslogng-server to template.
  hosts: iocage

  vars:

    iocage_jails: "{{ out.stdout | vbotka.freebsd.iocage('jails') }}"

  tasks:

    - name: Get iocage list of jails.
      register: out
      changed_when: false
      ansible.builtin.command: iocage list --long

    - name: Stop ansible-syslogng-server and convert it to template.
      when: iocage_jails is contains('ansible-syslogng-server')
      block:

        - name: Stop ansible-syslogng-server
          ansible.builtin.command: iocage stop ansible-syslogng-server

        - name: Convert ansible-syslogng-server jail to template.
          ansible.builtin.command: iocage set template=1 ansible-syslogng-server
