---
- name: Create jails from iocage templates.
  hosts: iocage_05

  tasks:

    - name: Create jail.
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-client
          alias=log_client"
      ansible.builtin.command: >
        iocage create
        --name log-client
        --template ansible-syslogng-client
        {{ properties | dictsort | map('join', '=') | join(' ') }}
        notes={{ _notes }}
