---
- name: Create jails from iocage templates.
  hosts: iocage_05

  tasks:

    - name: Create log-client
      vars:
        _notes: >
          "vmm={{ inventory_hostname }}
          class=log-client
          alias=log_client"
        _properties: >-
          {% for k, v in properties.items() %}
          {{ k }}={{ v }}
          {% endfor %}
          notes={{ _notes }}
      ansible.builtin.command: >
        iocage create
        --name log-client
        --template ansible-syslogng-client
        {{ _properties }}
