---
- name: Stop and convert ansible-syslogng-client to template.
  hosts: iocage_05

  tasks:

    - name: Stop ansible-syslogng-client
      ansible.builtin.command: iocage stop ansible-syslogng-client

    - name: Convert ansible-syslogng-client jail to template.
      ansible.builtin.command: iocage set template=1 ansible-syslogng-client
