fit_templates:
  ansible-init:
    release: 15.1-RELEASE
    pkg_conf: "{{ fit_pkg_conf | dict2items }}"
    pkg:
      - git
      - py312-ansible
    cron: "{{ fit_cron | dict2items }}"
    file_lines: "{{ fit_file_lines | dict2items }}"
    firstboot: "{{ fit_firstboot | dict2items }}"
    rcconf: "{{ fit_rcconf | dict2items }}"
    properties:
      ip4: disable
      ip6: disable
      ip6_addr: none
      bpf: 1
      dhcp: 1
      vnet: 1
      notes: '"class=init alias=ansible_init"'

fit_firstboot:
  ansible_init:
    content: "{{ lookup('ansible.builtin.file', 'files/ansible-init.sh', rstrip=False) }}"

fit_rcconf:
  ansible_init_enable: "YES"
  ansible_init_host: "git://{{ project_hosts[inventory_hostname]['repos'] }}"

fit_cron:
  /etc/cron.d/at:
    - name: Run atrun execution daemon in 1 minute intervals.
      minute: '*/1'
      hour: '*'
      day: '*'
      month: '*'
      weekday: '*'
      user: root
      job: /usr/libexec/atrun
      exclusive: true

fit_file_lines:
  /root/.profile:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
