---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: Set dictionary my_galaxy
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Set dictionary my_galaxy
      ansible.builtin.include_vars:
        file: ../galaxy.yml
        name: my_galaxy

    - name: Display my_galaxy dictionary
      ansible.builtin.debug:
        var: my_galaxy
