---
# All rights reserved (c) 2021, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Collection: vbotka.freebsd
# Playbook: setup.yml
#
# Description:
#
#   Setup collection vbotka.freebsd
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://github.com/vbotka/ansible-collection-freebsd/playbooks/setup.yml

- hosts: localhost
  gather_facts: false
  connection: local
  debugger: on_failed
  collections: vbotka.freebsd

  vars:
    my_version: "1.0.0"
    bsd_collection_dir: "{{ playbook_dir.split('/')[:-1]|join('/') }}"
    bsd_modules_setup:
      - iocage
      - ucl
    bsd_roles_setup:
      - ansible
      - ansible_lib
      - ansible_lint
      - ansible_runner
      - config_light

  vars_files:
    - vars/bsd-modules.yml
    - vars/bsd-roles.yml

  tasks:

    - name: "setup: Import setup-debug.yml"
      ansible.builtin.import_tasks: tasks/setup-debug.yml
      when: bsd_debug|d(false)|bool
      tags: setup_debug

    - name: "setup: Import setup-get-modules.yml"
      ansible.builtin.import_tasks: tasks/setup-get-modules.yml
      tags: setup_get_modules

    - name: "setup: Import setup-get-roles.yml"
      ansible.builtin.import_tasks: tasks/setup-get-roles.yml
      tags: setup_get_roles

# EOF
...
