---
- name: Configure, enable, and start Log Clients.
  hosts: log_client

  vars:

    log_server: "{{ hostvars['log-server']['iocage_ip4'] }}"

  tasks:

    - name: Display vars.
      when: debug | d(false) | bool
      ansible.builtin.debug:
        msg: |
          log_server: {{ log_server }}
          log_client: {{ groups.log_client }}

    - name: Configure LOG_SERVER
      ansible.builtin.lineinfile:
        dest: /usr/local/etc/syslog-ng.conf
        regexp: ^(.*)LOG_SERVER(.*)$
        line: '\g<1>{{ log_server }}\g<2>'
        backrefs: true
        backup: true
        validate: syslog-ng --syntax-only --cfgfile %s

    - name: Enable syslog-ng
      community.general.sysrc:
        name: syslog_ng_enable
        value: 'YES'

    - name: Start syslog-ng
      vbotka.freebsd.service:
        script: syslog-ng
        command: start
