---
# Copyright 2025 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Display iocage_jails_absent
  when: debug | d(false) | bool
  ansible.builtin.debug:
    var: iocage_jails_absent

- name: All jails already created. End host.
  when: iocage_jails_absent | length == 0
  ansible.builtin.meta: end_host

- name: Create jails.
  changed_when: false
  register: out_created
  ansible.builtin.command: >
    iocage create
    --name {{ item }}
    --template {{ vmm[inventory_hostname][item]['template'] }}
  loop: "{{ iocage_jails_absent }}"

- name: Display iocage_jails_created
  when: debug | d(false) | bool
  ansible.builtin.debug:
    var: iocage_jails_created

- name: Set properties.
  changed_when: false
  vars:
    _notes: >
      "vmm={{ inventory_hostname }}
      class={{ vmm[inventory_hostname][item]['class'] | join(',') }}"
    _properties: >
      {{ vmm[inventory_hostname][item]['properties']
         | d(properties)
         | dictsort | map('join', '=') | join(' ') }}
      notes={{ _notes }}
  ansible.builtin.command: >
    iocage set
    {{ _properties }}
    {{ item }}
  loop: "{{ iocage_jails_absent }}"
