---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: Create custom facts.
  vars:
    iocage_jails_facts: "{{ vmm[inventory_hostname]
                            | dict2items
                            | selectattr('value.custom_facts', 'defined') }}"
  block:

    - name: "Facts: Create custom facts dirs."
      ansible.builtin.file:
        state: directory
        path: "{{ iocage_mount }}/iocage/jails/{{ item.key }}/root{{ custom_facts_dir }}"
        owner: root
        group: wheel
        mode: '0755'
        recurse: true
      loop: "{{ iocage_jails_facts }}"
      loop_control:
        label: "{{ item.key }}"

    - name: "Facts: Create custom facts files."
      ansible.builtin.copy:
        dest: "{{ iocage_mount }}/iocage/jails/{{ item.key }}/root{{ custom_facts_path }}"
        owner: root
        group: wheel
        mode: '0755'
        content: |
          {{ lookup('ansible.builtin.template', item.value.custom_facts) }}
      loop: "{{ iocage_jails_facts }}"
      loop_control:
        label: "{{ item.key }}"
