---
# (c) 2026 Vladimir Botka <vbotka@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

- name: "Properties: Set properties."
  changed_when: false
  register: out
  vars:
    _properties: "{{ properties | d({})
                     | vbotka.freebsd.combine_properties(inventory_hostname, item) }}"
  ansible.builtin.command: >
    iocage set
    {{ _properties }}
    {{ item.key }}
  loop: "{{ vmm[inventory_hostname] | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Properties: Debug set properties."
  when: debug2 | d(false) | bool
  ansible.builtin.debug:
    var: out | d('none')
