---
# Copyright 2026 Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause
# SPDX-License-Identifier: BSD-2-Clause

- name: "Setup: Get activated pool."  # noqa: risky-shell-pipe
  register: out_pool
  changed_when: false
  ansible.builtin.shell: >
    zfs list -H -o name |
    grep '/iocage$' |
    cut -d'/' -f1

- name: "Setup: Display iocage_mount"
  when: debug | d(false) | bool
  ansible.builtin.debug:
    var: iocage_mount
